### PR TITLE
removed blade file

### LINKED ISSUE #8: Remove Blade files
We don't use blade as frontend template engine. Therefore we can delete the blade stuff in /ressources/views etc. Any linking to these files should be removed.

### PR DESCRIPTION
**Pull request by emso-sp**
Fixes #8 

In this PR, the blade file welcome.blade.php in resources/view is removed. This file has not been linked in any files in the backberry-directory. 

Since we are not using Laravel for frontend development, should I also remove all files in resources/css/ and resources/js as well as vite.config.js?

Thanks :smile:

### CODE REVIEW

**Comment by martincodes-de** [comment]
> Since we are not using Laravel for frontend development, should I also remove all files in resources/css/ and resources/js as well as vite.config.js?

yes would be great

**Review by martincodes-de — DISMISSED** [review]

**Review by GrafBunsen — CHANGES_REQUESTED** [review]
web.php should not be deleted. please restore

**Comment by GrafBunsen** [comment]
you have to merge develop into your feature branch again to fix the pipeline

**Comment by emso-sp** [comment]
done

**Comment by martincodes-de** [comment]
getting error if i visit `/`. i replace the template output with some simple stuff or remove it completly. after that, i would merge.

**Pull request merged**
